#!/bin/bash

if [[ $# -ne 2 ]]; then
    echo "Usage: connect-database <your-project> <database-name>"
    exit 1
fi

cd "$1"
sed -i "s|^DATABASE_URL=.*|DATABASE_URL="postgresql://postgres:postgres@localhost:5432/$2?schema=public"|" .env
